spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://sca-orporas-t;databaseName=MTIWeb;encrypt=false;trustServerCertificate=false;
    password: lethn34olj
    username: devMTIWeb
  jpa:
    database: sql_server
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
server:
  port: 7070
